### ISSUE TITLE
Fails to build with latest Hackage (tasty 1.4.0.3)

### ISSUE THREAD

**Issue by vmchale** [feuerbach/tasty-html#22]
Error as follows:

```
[2 of 2] Compiling Test.Tasty.Runners.Html ( Test/Tasty/Runners/Html.hs, /private/tmp/tasty-html-0.4.1.2/dist-newstyle/build/x86_64-osx/ghc-8.10.3/tasty-html-0.4.1.2/build/Test/Tasty/Runners/Html.o, /private/tmp/tasty-html-0.4.1.2/dist-newstyle/build/x86_64-osx/ghc-8.10.3/tasty-html-0.4.1.2/build/Test/Tasty/Runners/Html.dyn_o )

Test/Tasty/Runners/Html.hs:90:48: error:
    • Couldn't match type ‘Traversal
                             (Compose (StateT Int IO) (Const Summary))’
                     with ‘Traversal (Compose (StateT Int IO) (Const Summary))
                           -> Traversal (Compose (StateT Int IO) (Const Summary))’
      Expected type: OptionSet
                     -> TestName
                     -> Traversal (Compose (StateT Int IO) (Const Summary))
                     -> Traversal (Compose (StateT Int IO) (Const Summary))
        Actual type: TestName -> SummaryTraversal -> SummaryTraversal
    • In the ‘foldGroup’ field of a record
      In the first argument of ‘Tasty.foldTestTree’, namely
        ‘Tasty.trivialFold
           {Tasty.foldSingle = runTest statusMap, Tasty.foldGroup = runGroup}’
      In the second argument of ‘($)’, namely
        ‘Tasty.foldTestTree
           Tasty.trivialFold
             {Tasty.foldSingle = runTest statusMap, Tasty.foldGroup = runGroup}
           options testTree’
   |
90 |                           , Tasty.foldGroup  = runGroup
```

**Comment by vmchale** [comment]
Seems to work with `tasty <1.4`.

**Comment by feuerbach** [comment]
Thanks for the report. This should be fixed now in tasty-html-0.4.1.4.
