### ISSUE TITLE
Does not compile with GHC 8.4.*

### ISSUE THREAD

**Issue by taktoa** [feuerbach/tasty-html#19]
```
[1 of 2] Compiling Paths_tasty_html ( dist/build/autogen/Paths_tasty_html.hs, dist/build/Paths_tasty_html.o )
[2 of 2] Compiling Test.Tasty.Runners.Html ( Test/Tasty/Runners/Html.hs, dist/build/Test/Tasty/Runners/Html.o )

Test/Tasty/Runners/Html.hs:115:10: error:
    • No instance for (Semigroup Summary)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid Summary’
    |
115 | instance Monoid Summary where
    |          ^^^^^^^^^^^^^^
```

Should be an easy fix: just write the instance of `Semigroup` for `Summary`.

**Comment by feuerbach** [comment]
Thanks for the notice — should be fixed in the version 0.4.1.2.
